apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service-controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          limits:
            cpu: 555m
            memory: 1Gi
          requests:
            cpu: 111m
            memory: 20Mi
