---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: add-rh-certs-patch.yaml
    target:
      name: controller-manager
      kind: Deployment

resources:
  - trusted-ca-cfg.yaml

namespace: integration-service
