apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: trusted-ca
  namespace: system
